# Placeholder for internal Python library.

package(
    default_visibility = [
        "//tensorflow_recommenders_addons:__subpackages__",
    ],
)

licenses(["notice"])  # Apache 2.0

py_library(
    name = "optimizer_ops",
    srcs = glob(["*.py"]),
    srcs_version = "PY2AND3",
)
