package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cuckoohash",
    hdrs = [
        "cuckoohash_config.hh",
        "cuckoohash_map.hh",
        "cuckoohash_util.hh",
        "libcuckoo_bucket_container.hh",
    ],
)
