# Placeholder for internal Python library.
# Placeholder for internal Python test library.

package(
    default_visibility = [
        "//tensorflow_recommenders_addons:__subpackages__",
    ],
)

licenses(["notice"])  # Apache 2.0

# Tests
py_test(
    name = "dynamic_embedding_variable_test",
    srcs = ["dynamic_embedding_variable_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

py_test(
    name = "dynamic_embedding_ops_test",
    srcs = ["dynamic_embedding_ops_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

py_test(
    name = "dynamic_embedding_optimizer_test",
    srcs = ["dynamic_embedding_optimizer_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

py_test(
    name = "restrict_policies_test",
    srcs = ["restrict_policies_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

py_test(
    name = "shadow_embedding_ops_test",
    srcs = ["shadow_embedding_ops_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

py_test(
    name = "cuckoo_hashtable_ops_test",
    srcs = ["cuckoo_hashtable_ops_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

# This test will be banned by GitHub and cause account violations, please run the test manually locally.
# py_test(
#     name = "redis_table_variable_test",
#     srcs = ["redis_table_variable_test.py"],
#     python_version = "PY3",
#     srcs_version = "PY3",
#     deps = [
#         "//tensorflow_recommenders_addons",
#     ],
# )

py_test(
    name = "math_ops_test",
    srcs = ["math_ops_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

py_test(
    name = "math_grad_test",
    srcs = ["math_grad_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

py_test(
    name = "dynamic_partition_op_test",
    srcs = ["dynamic_partition_op_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

py_test(
    name = "dynamic_stitch_op_test",
    srcs = ["dynamic_stitch_op_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)
