# Placeholder for internal Python library.
# Placeholder for internal Python test library.

package(
    default_visibility = [
        "//tensorflow_recommenders_addons:__subpackages__",
    ],
)

licenses(["notice"])  # Apache 2.0

# Tests
py_test(
    name = "dynamic_embedding_variable_test",
    srcs = ["dynamic_embedding_variable_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

py_test(
    name = "dynamic_embedding_ops_test",
    srcs = ["dynamic_embedding_ops_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

py_test(
    name = "dynamic_embedding_optimizer_test",
    srcs = ["dynamic_embedding_optimizer_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

py_test(
    name = "restrict_policies_test",
    srcs = ["restrict_policies_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)

py_test(
    name = "cuckoo_hashtable_ops_test",
    srcs = ["cuckoo_hashtable_ops_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders_addons",
    ],
)
