# Placeholder for internal Python library.

# TensorFlow Recommenders-Addons, a TensorFlow library for building recommender systems.
package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files(["LICENSE"])

py_library(
    name = "tensorflow_recommenders_addons",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
    deps = [
        "//tensorflow_recommenders-addons/dynamic_embedding",
    ],
)
