licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

py_library(
    name = "utils",
    srcs = glob(["*.py"]),
    data = [
        "//tensorflow_recommenders_addons:conftest.py",
    ],
)
